spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates: #los predicates son reglas del request que deven cumplirse si o si
          - Path=/api/productos/**
          - Header= token, \d+
          - Header= Content-Type, application/json
          - Method=GET, POST
          - Query=color
          - Cookie=color, rojo
        filters:
          - StripPrefix=2
          - EjemploCookie=Hola mi mensaje personalizado, usuario, GamalielAbanto
          # - name: Ejemplo
            # args:
            #   message: "Hola mi mensaje personalizado"
            #   cookieNombre: "usuario"
            #   cookieValor: "GamalielAbanto"
          
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 12345678
          - SetResponseHeader=Content-Type, text/plain
          - AddRequestParameter=nombre, andres